#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Kazuma Ohashi
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s): 
    try:     
       return int(S)
    except:
       return float(s)


ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)
       
print(ans)
